package userdetail

type UserDetail struct {
	ID                        int64  `json:"id"`
	UserID                    string `json:"user_id"`
	UserName                  string `json:"user_name"`
	FirstName                 string `json:"first_name"`
	LastName                  string `json:"last_name"`
	Email                     string `json:"email"`
	Enabled                   string `json:"enabled"`
	Role                      string `json:"role"`
	Password                  string `json:"password"`
	ParentID                  string `json:"parent_id"`
	Secret                    string `json:"secret"`
	MFAEnabled                string `json:"mfa_enabled"`
	Type                      string `json:"type"`
	IsStaffMember             string `json:"is_staff_member"`
	Organization              string `json:"organization"`
	DOB                       string `json:"dob"`
	Gender                    string `json:"gender"`
	Phone                     string `json:"phone"`
	OpenStackUserID           string `json:"openstack_user_id"`
	Status                    string `json:"status"`
	Active                    string `json:"active"`
	Image                     string `json:"image"`
	UpdatedBy                 string `json:"updated_by"`
	CreatedAt                 string `json:"created_at"`
	UpdatedAt                 string `json:"updated_at"`
	HystaxID                  string `json:"hystax_id"`
	RoleName                  string `json:"role_name"`
	OpenStackDefaultProjectID string `json:"openstack_default_project_id"`
	OpenStackID               string `json:"openstack_id"`
	OtpEnabled                string `json:"otp_enabled"`
	Description               string `json:"description"`
	StripeID                  string `json:"stripe_id"`
	CardDetail                string `json:"card_detail"`
	Address                   string `json:"address"`
	AllowCredit               string `json:"allow_credit"`
	City                      string `json:"city"`
	CodeExpiration            string `json:"code_expiration"`
	Country                   string `json:"country"`
	AgreedTermsVersion        string `json:"agreed_terms_version"`
	EmailVerified             string `json:"email_verified"`
	IsEnforced                string `json:"is_enforced"`
	State                     string `json:"state"`
	VerificationCode          string `json:"verification_code"`
	VerifyPhone               string `json:"verify_phone"`
	AllowFreeCredit           string `json:"allow_free_credit"`
	CreditLimitDate           string `json:"credit_limit_date"`
	CardExemption             string `json:"card_exemption"`
	CurrentStep               string `json:"current_step"`
	CardExcemption            string `json:"card_excemption"`
	CreaditLimitDate          string `json:"creadit_limit_date"`
	CurrentAgreedTermsVersion string `json:"current_agreed_terms_version"`
	EnforceEnabled            string `json:"enforce_enabled"`
	Firstname                 string `json:"firstname"`
	Lastname                  string `json:"lastname"`
	Test                      string `json:"test"`
	Username                  string `json:"username"`
	IsPasswordReset           string `json:"is_password_reset"`
	EmiratesID                string `json:"emirates_id"`
	Fax                       string `json:"fax"`
	PhoneNumber               string `json:"phone_number"`
	Pobox                     string `json:"pobox"`
	TenantID                  string `json:"tenant_id"`
	NTNNo                     string `json:"ntn_no"`
}

type UpdatePatch map[string]string
